# Generated by Django 3.0.7 on 2020-07-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigndata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marriage',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(fields=('spouse1', 'spouse2'), name='unique_marriage'),
        ),
    ]
